### ISSUE TITLE
Is there a way to customize the style of 'displayTrackTooltip'?

### ISSUE THREAD

**Issue by hyejinc-dev** [lipme/vue-svg-msa#1]
Thank you for the great work with vue-svg-msa.
I wanted to customize the style of 'displayTrackTooltip', so I found out that you are using the 'vue-svg-tracks' package.
Surfing for 'vue-svg-tracks' did not find a way because the git storage code was not connected.
Is there a way to customize the style of 'displayTrackTooltip'?
Thank you.

**Comment by lipme** [comment]
Thanks for using vue-svg-msa !
There is no way for customizing the style of displayTrackTooltip from vue-svg-msa but you can do it directly in vue-svg-tracks : we just gave access to the repository (it was a mistake) : 
https://github.com/lipme/vue-svg-tracks
